# Generated by Django 4.2.7 on 2023-11-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_performer_id', models.UUIDField()),
                ('action_performed_on_id', models.UUIDField()),
                ('last_updated_time_of_strength', models.DateField(auto_now=True)),
                ('label_performer', models.CharField(choices=[('Us', 'User'), ('Po', 'Post'), ('Ca', 'Category')], max_length=2)),
                ('label_performed_on', models.CharField(choices=[('Us', 'User'), ('Po', 'Post'), ('Ca', 'Category')], max_length=2)),
                ('strength', models.IntegerField(default=1)),
                ('strength_latest', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
