# Generated by Django 4.2.7 on 2023-11-17 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_remove_follower_last_updated_time_of_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2023, 11, 3)),
        ),
    ]
