# Generated by Django 4.2.7 on 2023-11-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_post_date_delete_newpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('edit_and_add_posts_of_others', 'Can edit and add posts of others')]},
        ),
    ]
