# Generated by Django 4.2.7 on 2023-11-21 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_remove_interaction_last_updated_time_of_strength_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sellerId',
        ),
        migrations.AddField(
            model_name='notification',
            name='image_from',
            field=models.CharField(choices=[('U', 'User'), ('P', 'Post')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notifyUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='postId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='notification',
            name='profileId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
