# Generated by Django 4.2.7 on 2023-11-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0049_alter_interactionusertocategory_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='engagement',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
