# Generated by Django 4.2.7 on 2023-11-29 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
