# Generated by Django 4.2.7 on 2023-12-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0054_alter_post_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_in_category', to='posts.category'),
        ),
    ]
