# Generated by Django 4.2.7 on 2023-12-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0055_alter_ads_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.category'),
        ),
    ]
