# Generated by Django 4.2.7 on 2023-12-29 20:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0057_paymethod_ads_payverified_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 15, 27, 9, 125936)),
        ),
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 15, 27, 9, 110314)),
        ),
        migrations.AddField(
            model_name='paymethod',
            name='accountNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 15, 27, 9, 125936)),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionConfirmationCode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 15, 27, 9, 110314)),
        ),
        migrations.AlterField(
            model_name='ads',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ads', to='posts.transaction'),
        ),
    ]
