# Generated by Django 4.2.7 on 2023-12-29 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0058_ads_created_at_image_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 15, 27, 27, 456482)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 15, 27, 27, 456482)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 15, 27, 27, 456482)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 15, 27, 27, 455416)),
        ),
    ]
