# Generated by Django 4.2.7 on 2023-12-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0060_alter_ads_created_at_alter_image_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionConfirmationCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
