# Generated by Django 4.2.7 on 2023-12-29 21:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0061_alter_transaction_transactionconfirmationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymethod',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='verificationScreenshot',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
