# Generated by Django 4.2.7 on 2023-12-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0062_paymethod_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymethod',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
