# Generated by Django 4.2.7 on 2024-01-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0064_transaction_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='coin_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pay_for',
            field=models.CharField(choices=[('A', 'Ads'), ('P', 'Package')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
