# Generated by Django 4.2.7 on 2024-01-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0065_transaction_coin_amount_transaction_pay_for_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_amount_in_words', models.CharField(max_length=100)),
                ('coin_amount_in_number', models.IntegerField()),
                ('hasDiscount', models.BooleanField()),
                ('originalPriceCurrency', models.CharField(blank=True, choices=[('Br', 'Birr')], max_length=5, null=True)),
                ('discountPriceCurrency', models.CharField(blank=True, choices=[('Br', 'Birr')], max_length=5, null=True)),
                ('original_price_in_words', models.CharField(max_length=100)),
                ('discounted_price_in_words', models.CharField(blank=True, default='', max_length=100)),
                ('level_of_payment_1_through_4', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['-order', 'coin_amount_in_number'],
            },
        ),
    ]
