# Generated by Django 4.2.7 on 2024-01-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0067_alter_package_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
