# Generated by Django 4.2.7 on 2024-01-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0068_alter_package_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
