# Generated by Django 3.2.23 on 2024-08-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0071_auto_20240810_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=25)),
                ('android_id', models.CharField(max_length=25)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
