# Generated by Django 4.2.7 on 2023-11-10 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_engagement_newpost_interactionusertouser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationcategorytoseller',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_to_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user_followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user_follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interactionusertocategory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_with_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interactionusertopost',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_with_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interactionusertouser',
            name='user_performed_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interactionusertouser',
            name='user_performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
