# Generated by Django 4.2.7 on 2023-11-15 21:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_nexticonaction_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended',
            name='postId',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
