# Generated by Django 4.2.7 on 2023-11-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seen',
            name='count',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=24),
        ),
    ]
