# Generated by Django 4.2.7 on 2023-11-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_seen_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='last_updated_time_of_strength',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='strength_over_time',
        ),
        migrations.AlterField(
            model_name='seen',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
