# Generated by Django 4.2.7 on 2023-11-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='strength',
            new_name='engagement',
        ),
        migrations.RemoveField(
            model_name='associationcategorytoseller',
            name='last_updated_time_of_strength',
        ),
        migrations.RemoveField(
            model_name='associationcategorytoseller',
            name='strength_over_time',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='strength_latest',
        ),
        migrations.RemoveField(
            model_name='interactionusertocategory',
            name='last_updated_time_of_strength',
        ),
        migrations.RemoveField(
            model_name='interactionusertocategory',
            name='strength_over_time',
        ),
        migrations.RemoveField(
            model_name='interactionusertopost',
            name='last_updated_time_of_strength',
        ),
        migrations.RemoveField(
            model_name='interactionusertopost',
            name='strength_over_time',
        ),
        migrations.RemoveField(
            model_name='interactionusertouser',
            name='last_updated_time_of_strength',
        ),
        migrations.RemoveField(
            model_name='interactionusertouser',
            name='strength_over_time',
        ),
    ]
