# Generated by Django 4.2.7 on 2023-11-21 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_remove_notification_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image_from',
            field=models.CharField(choices=[('U', 'User'), ('P', 'Post')], max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifyUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
