# Generated by Django 4.2.7 on 2023-11-21 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_alter_notification_image_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='postId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='profileId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
