# Generated by Django 4.2.7 on 2023-11-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_delete_interaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='phone',
        ),
    ]
