# Generated by Django 4.2.7 on 2023-11-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_remove_notification_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
    ]
