# Generated by Django 4.2.7 on 2023-11-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_alter_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='seen',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='favourite',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='seen',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
