# Generated by Django 4.2.7 on 2023-11-22 12:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_alter_user_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sellerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 12, 0, 29, 239414, tzinfo=datetime.timezone.utc)),
        ),
    ]
