# Generated by Django 4.2.7 on 2023-11-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0046_alter_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.TextField(blank=True, default=''),
        ),
    ]
